a = input("Digite algo :")
print('O tipo primitivo desse valor é', type(a))
print("Só tem espaco ?" , a.isspace())
print("É um número? ", a.isnumeric())
print("É alfabético?", a.isalpha())
print("É alfanumérico?", a.isalnum())
print("Está em maisculo?", a.isupper())
print("Está em minuscula?", a.islower())
